version: '3.3'

# Ericom Shield Stack Description
# YML file for Rel-18.08 Browsers Farm Components

services:
    netdata:
        image: 'securebrowsing/netdata:latest'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        networks:
            - shield-rbf
        hostname: netdata
        ports:
            - {target: 19999, published: 8384, protocol: tcp}
        deploy:
            mode: global
            restart_policy: {condition: any}
            update_config: {failure_action: rollback}
            resources: {limits: {cpus: '0.20', memory: 256M}}
# netdata will not be deployed by default (need to add label:netdata):            
            placement: {constraints: [node.labels.netdata==yes]}
        environment:
            - 'TZ=UTC'
    maintenance:
        image: 'securebrowsing/shield-maintenance:latest'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        networks:
            - shield-rbf
        hostname: maintenance
        deploy:
            mode: global
            restart_policy: {condition: any}
            update_config: {failure_action: rollback}
            resources: {limits: {memory: 2GB, cpus: '0.5'}}
        environment:
            - 'TZ=UTC'
            - 'IMAGE_CLEAN_INTERVAL=1h'
            - 'RUN_TIME=23:59'
            - 'LOGSTASH_FIELDS=service=maintenance'
    collector:
        image: 'securebrowsing/shield-collector:latest'
        networks:
            - shield-rbf
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/dev:/hostdev'
        hostname: '{{.Node.ID}}-{{.Service.Name}}'
        environment:
            - 'TZ=UTC'
            - 'NODE_ENV=production'
            - 'LOGSTASH_FIELDS=service=collector'
        deploy:
            mode: global
            restart_policy: {condition: any}
            update_config: {failure_action: rollback}
    logspout:
        image: 'securebrowsing/shield-logspout:latest'
        networks:
            - shield-rbf
        volumes:
            - '/etc/hostname:/etc/host_hostname:ro'
            - '/var/run/docker.sock:/var/run/docker.sock'
        environment:
            - 'TZ=UTC'
            - 'ROUTE_URIS=logstash+tcp://elk:5025'
            - 'RETRY_STARTUP=true'
            #- "DEBUG=1"
        deploy:
            mode: global
            resources: {limits: {cpus: '0.20', memory: 256M}, reservations: {cpus: '0.10', memory: 128M}}
    consul-server:
        image: 'securebrowsing/shield-configuration:latest'
        networks:
            - shield-rbf
        deploy:
            mode: replicated   #single node
            replicas: 5        #single node
            #mode: global      #multi node
            endpoint_mode: dnsrr
            placement: {constraints: [node.labels.management==yes]}
            update_config: {parallelism: 1, failure_action: rollback, delay: 100s}
            restart_policy: {condition: any}
            resources: {limits: {memory: 1GB, cpus: '1'}}
        environment:
            - 'TZ=UTC'
            - 'CONSUL_BIND_INTERFACE=eth0'
            - 'NUMBER_OF_EXPECTED=3' # works for single and multi node
            - 'LOGSTASH_FIELDS=service=consulserver'
        volumes:
            - {type: bind, source: /usr/local/ericomshield/backup, target: /consul/backup}
    consul:
        image: 'securebrowsing/shield-consul-agent:latest'
        networks:
            - shield-rbf
        #Published only for Dev    
        ports:
            - '8501:8500'
        deploy:
            mode: replicated
            replicas: 1
            update_config: {parallelism: 1, failure_action: rollback}
            restart_policy: {condition: any}
            resources: {limits: {memory: 1GB, cpus: '1'}}
        environment:
            - 'TZ=UTC'
            # eth2 for Dev
            - 'CONSUL_BIND_INTERFACE=eth2'
            - 'RUN_AGENT=yes'
            - 'LOGSTASH_FIELDS=service=consulclient'

###################################################################### Shield services part ##################################################################
    shield-browser:
        image: 'securebrowsing/shield-cef:latest'
        user: user
        ulimits:
            nice: -20
            rtprio: 10
        labels:
            - com.ericom.browser
        environment:
            - 'TZ=UTC'
            #- 'FPS=25'
            #- 'DEBUG_REMOTE_SITE=true'
            #- 'DISPOSE_BROWSER=true'
            #- 'RUN_WITH_DEBUGGER=false'
            #- 'EXTProxyAddress='
            #- 'DEBUG_SEND_LOG_TO_AN=true'
            - 'SHIELD_NODE_NAME={{.Node.Hostname}}'
            - 'SHIELD_SERVICE_NAME={{.Service.Name}}'
            - 'PERF_STATS=true'
            - 'LOGSTASH_FIELDS=service=browser'
        networks:
            - shield-rbf
        deploy:
            mode: replicated
            replicas: 20
            endpoint_mode: dnsrr
            update_config: {parallelism: 8, delay: 10s}
            restart_policy: {condition: any}
            resources: {limits: {memory: 1GB, cpus: '2'}, reservations: {cpus: '0.2', memory: 150MB}}
            placement: {constraints: [node.labels.browser==yes]}
        volumes:
            - {type: tmpfs, target: /dev/shm}
            - {type: tmpfs, target: /home}
            - {type: tmpfs, target: /tmp}
            - {type: bind, target: /dev/shm/xorg, source: /media/containershm}
    ext-proxy:
        image: 'securebrowsing/extproxy:latest'
        hostname: ext-proxy
        ulimits:
            nofile: {soft: 65535, hard: 65535}
        networks:
            - shield-rbf
        deploy:
            mode: replicated
            replicas: 2
            placement: {constraints: [node.labels.browser==yes]}
            resources: {limits: {memory: 1024MB, cpus: '1'}}
        environment:
            - 'TZ=UTC'
    ext-proxy-noadblock:
        image: 'securebrowsing/extproxy:latest'
        hostname: ext-proxy-noadblock
        ulimits:
            nofile: {soft: 65535, hard: 65535}
        networks:
            - shield-rbf
        deploy:
            mode: replicated
            replicas: 2
            placement: {constraints: [node.labels.browser==yes]}
            resources: {limits: {memory: 1024MB, cpus: '1'}}
        environment:
            - 'TZ=UTC'
            - 'ADDBLOCK=no'
    speedtest:
        image: 'securebrowsing/speedtest:latest'
        hostname: speedtest
        ports:
            - '8185:8185'
        networks:
            - shield-rbf
        deploy:
            mode: replicated
            replicas: 1
            placement: {constraints: [node.labels.browser==yes]}
            resources: {limits: {memory: 512MB, cpus: '0.5'}}
        environment:
            - 'TZ=UTC'

networks:
    shield-rbf:
        driver: overlay
        ipam:
            driver: default
            config: [{subnet: 10.21.0.0/16}]
